CREATE TABLE DIM_HORA (
                SK_HORA VARCHAR(4) NOT NULL,
                HORA SMALLINT NOT NULL,
                MINUTO SMALLINT NOT NULL,
                SEGUNDO DATETIME NOT NULL,
                PADRAO CHAR(2) NOT NULL,
                PERIODO VARCHAR(20) NOT NULL,
                PERIODO_ORDER SMALLINT NOT NULL,
                CONSTRAINT dim_hora_pk PRIMARY KEY (SK_HORA)
)

CREATE TABLE DIM_FORMA_PAGTO (
                SK_FORMA_PAGTO INT NOT NULL,
                NK_FORMA_PAGTO INT NOT NULL,
                NM_FORMA_PAGTO VARCHAR(50) NOT NULL,
                ETL_VERSAO INT NOT NULL,
                ETL_DT_INICIO DATETIME NOT NULL,
                ETL_DT_FIM DATETIME NOT NULL,
                CONSTRAINT dim_forma_pagto_pk PRIMARY KEY (SK_FORMA_PAGTO)
)

CREATE TABLE DIM_CANDIDATO (
                SK_CANDIDATO INT NOT NULL,
                NK_CANDIDATO INT NOT NULL,
                NM_CANDIDATO VARCHAR(50) NOT NULL,
                ETL_VERSAO INT NOT NULL,
                ETL_DT_INICIO DATETIME NOT NULL,
                ETL_DT_FIM DATETIME NOT NULL,
                CONSTRAINT DIM_CANDIDATO_pk PRIMARY KEY (SK_CANDIDATO)
)

CREATE TABLE DIM_DATA (
                SK_DATA VARCHAR(10) NOT NULL,
                DIA INT NOT NULL,
                MES INT NOT NULL,
                NM_MES VARCHAR(30) NOT NULL,
                ANO INT NOT NULL,
                DATA DATETIME NOT NULL,
                CONSTRAINT DIM_DATA_pk PRIMARY KEY (SK_DATA)
)

CREATE TABLE DIM_PROCESSO (
                SK_PROCESSO INT NOT NULL,
                NK_PROCESSO INT NOT NULL,
                NM_PROCESSO VARCHAR(50) NOT NULL,
                PERIODO_LETIVO VARCHAR(10) NOT NULL,
                ETL_VERSAO INT NOT NULL,
                ETL_DT_INICIO DATETIME NOT NULL,
                ETL_DT_FIM DATETIME NOT NULL,
                CONSTRAINT DIM_PROCESSO_pk PRIMARY KEY (SK_PROCESSO)
)

CREATE TABLE DIM_CURSO (
                SK_CURSO INT NOT NULL,
                NK_CURSO INT NOT NULL,
                NM_CURSO VARCHAR(50) NOT NULL,
                ETL_VERSAO INT NOT NULL,
                ETL_DT_INICIO DATETIME NOT NULL,
                ETL_DT_FIM DATETIME NOT NULL,
                CONSTRAINT DIM_CURSO_pk PRIMARY KEY (SK_CURSO)
)

CREATE TABLE FATO_PRE_INSCRICOES (
                SK_CANDIDATO INT NOT NULL,
                SK_CURSO INT NOT NULL,
                SK_PROCESSO INT NOT NULL,
                SK_DATA VARCHAR(10) NOT NULL,
                SK_HORA VARCHAR(4) NOT NULL,
                CONSTRAINT fato_pre_inscricoes_pk PRIMARY KEY (SK_CANDIDATO, SK_CURSO, SK_PROCESSO, SK_DATA, SK_HORA)
)

CREATE TABLE FATO_INSCRICOES (
                SK_CANDIDATO INT NOT NULL,
                SK_CURSO INT NOT NULL,
                SK_PROCESSO INT NOT NULL,
                SK_DATA VARCHAR(10) NOT NULL,
                SK_HORA VARCHAR(4) NOT NULL,
                BOLSA_ESTUDO INT NOT NULL,
                CALL_CENTER INT NOT NULL,
                CONSTRAINT fato_inscricoes_pk PRIMARY KEY (SK_CANDIDATO, SK_CURSO, SK_PROCESSO, SK_DATA, SK_HORA)
)

CREATE TABLE FATO_INSCRICOES_PAGAS (
                SK_CANDIDATO INT NOT NULL,
                SK_CURSO INT NOT NULL,
                SK_PROCESSO INT NOT NULL,
                SK_DATA VARCHAR(10) NOT NULL,
                SK_HORA VARCHAR(4) NOT NULL,
                SK_FORMA_PAGTO INT NOT NULL,
                CALL_CENTER INT NOT NULL,
                BOLSA_ESTUDO INT NOT NULL,
                VALOR DECIMAL(10,2) NOT NULL,
                CONSTRAINT fato_inscricoes_pagad_pk PRIMARY KEY (SK_CANDIDATO, SK_CURSO, SK_PROCESSO, SK_DATA, SK_HORA, SK_FORMA_PAGTO)
)

ALTER TABLE FATO_INSCRICOES ADD CONSTRAINT DIM_HORA_FATO_INSCRICOES_fk
FOREIGN KEY (SK_HORA)
REFERENCES DIM_HORA (SK_HORA)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE FATO_PRE_INSCRICOES ADD CONSTRAINT DIM_HORA_FATO_PRE_INSCRICOES_fk
FOREIGN KEY (SK_HORA)
REFERENCES DIM_HORA (SK_HORA)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE FATO_INSCRICOES_PAGAS ADD CONSTRAINT DIM_HORA_FATO_INSCRICOES_PAGAS_fk
FOREIGN KEY (SK_HORA)
REFERENCES DIM_HORA (SK_HORA)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE FATO_INSCRICOES_PAGAS ADD CONSTRAINT DIM_FORMA_PAGTO_FATO_INSCRICOES_PAGAS_fk
FOREIGN KEY (SK_FORMA_PAGTO)
REFERENCES DIM_FORMA_PAGTO (SK_FORMA_PAGTO)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE FATO_PRE_INSCRICOES ADD CONSTRAINT DIM_CANDIDATO_FATO_PRE_INSCRICOES_fk
FOREIGN KEY (SK_CANDIDATO)
REFERENCES DIM_CANDIDATO (SK_CANDIDATO)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE FATO_INSCRICOES ADD CONSTRAINT DIM_CANDIDATO_FATO_INSCRICOES_fk
FOREIGN KEY (SK_CANDIDATO)
REFERENCES DIM_CANDIDATO (SK_CANDIDATO)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE FATO_INSCRICOES_PAGAS ADD CONSTRAINT DIM_CANDIDATO_FATO_INSCRICOES_PAGAS_fk
FOREIGN KEY (SK_CANDIDATO)
REFERENCES DIM_CANDIDATO (SK_CANDIDATO)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE FATO_PRE_INSCRICOES ADD CONSTRAINT DIM_DATA_FATO_PRE_INSCRICOES_fk
FOREIGN KEY (SK_DATA)
REFERENCES DIM_DATA (SK_DATA)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE FATO_INSCRICOES ADD CONSTRAINT DIM_DATA_FATO_INSCRICOES_fk
FOREIGN KEY (SK_DATA)
REFERENCES DIM_DATA (SK_DATA)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE FATO_INSCRICOES_PAGAS ADD CONSTRAINT DIM_DATA_FATO_INSCRICOES_PAGAS_fk
FOREIGN KEY (SK_DATA)
REFERENCES DIM_DATA (SK_DATA)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE FATO_PRE_INSCRICOES ADD CONSTRAINT DIM_PROCESSO_FATO_PRE_INSCRICOES_fk
FOREIGN KEY (SK_PROCESSO)
REFERENCES DIM_PROCESSO (SK_PROCESSO)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE FATO_INSCRICOES ADD CONSTRAINT DIM_PROCESSO_FATO_INSCRICOES_fk
FOREIGN KEY (SK_PROCESSO)
REFERENCES DIM_PROCESSO (SK_PROCESSO)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE FATO_INSCRICOES_PAGAS ADD CONSTRAINT DIM_PROCESSO_FATO_INSCRICOES_PAGAS_fk
FOREIGN KEY (SK_PROCESSO)
REFERENCES DIM_PROCESSO (SK_PROCESSO)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE FATO_INSCRICOES_PAGAS ADD CONSTRAINT DIM_CURSO_FATO_INSCRICOES_PAGAS_fk
FOREIGN KEY (SK_CURSO)
REFERENCES DIM_CURSO (SK_CURSO)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE FATO_INSCRICOES ADD CONSTRAINT DIM_CURSO_FATO_INSCRICOES_fk
FOREIGN KEY (SK_CURSO)
REFERENCES DIM_CURSO (SK_CURSO)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE FATO_PRE_INSCRICOES ADD CONSTRAINT DIM_CURSO_FATO_PRE_INSCRICOES_fk
FOREIGN KEY (SK_CURSO)
REFERENCES DIM_CURSO (SK_CURSO)
ON DELETE NO ACTION
ON UPDATE NO ACTION