DECLARE @DIM_HORA TABLE
(
	SK_HORA VARCHAR(4) NOT NULL PRIMARY KEY,
	HORA SMALLINT NOT NULL,
	MINUTO SMALLINT NOT NULL,
	PADRAO CHAR(2) NOT NULL,
	PERIODO VARCHAR(20) NULL,
	PERIODO_ORDER SMALLINT NULL
)

DECLARE @startdate DATETIME
DECLARE @enddate DATETIME
DECLARE @date DATETIME

SET @startdate = '1/1/2021 12:00:00 AM'   
SET @enddate = '1/1/2021 23:59:59 PM'  
SET @date = @startdate

WHILE @date <= @enddate
BEGIN
    INSERT INTO @DIM_HORA 
		(SK_HORA, HORA, MINUTO, PADRAO, PERIODO, PERIODO_ORDER)
    VALUES 
		(
			REPLACE(CONVERT(VARCHAR(5), @date, 108), ':', ''),
			CONVERT(VARCHAR(2), @date, 108),
			DATEPART(mi, @date),
			CASE 
				WHEN DATEPART(hh, @date) BETWEEN 0 AND 11 THEN 'AM' 
				ELSE 'PM' 
			END,
			CASE
				WHEN DATEPART(hh, @date) BETWEEN 0 AND 5 THEN 'Madrugada'
				WHEN DATEPART(hh, @date) BETWEEN 6 AND 11 THEN 'Manhã'
				WHEN DATEPART(hh, @date) BETWEEN 12 AND 17 THEN 'Tarde'
				ELSE 'Noite'
			END,
			CASE
				WHEN DATEPART(hh, @date) BETWEEN 0 AND 5 THEN 1
				WHEN DATEPART(hh, @date) BETWEEN 6 AND 11 THEN 2
				WHEN DATEPART(hh, @date) BETWEEN 12 AND 17 THEN 3
				ELSE 4
			END 
		)

    SET @date = DATEADD(mi, 1, @date)
END

SELECT * FROM @DIM_HORA