CREATE PROCEDURE SP_INSERT_DIM_TEMPO
@DATAINICIAL DATE, @DATAFINAL DATE
AS
BEGIN
	DECLARE 
	@SK_DATA VARCHAR(10),
	@DATA DATE,
	@COD_SEMANA INT,
	@DIA_SEMANA INT,
	@NOME_DIA_SEMANA VARCHAR(20),
	@DIA INT,
	@MES INT,
	@NOME_MES VARCHAR(20),
	@MES_ANO VARCHAR(12),
	@NOME_MES_ANO VARCHAR(30),
	@TRIMESTRE INT,
	@NOME_TRIMESTRE VARCHAR(20),
	@TRIMESTRE_ANO VARCHAR(12),
	@NOME_TRIMESTRE_ANO VARCHAR(30),
	@SEMESTRE INT,
	@NOME_SEMESTRE VARCHAR(20),
	@SEMESTRE_ANO VARCHAR(12),
	@NOME_SEMESTRE_ANO VARCHAR(30),
	@ANO INT,
	@TIPO_DIA VARCHAR(20)

	WHILE @DATAINICIAL <= @DATAFINAL
	BEGIN
		SET @SK_DATA = FORMAT(@DATAINICIAL, 'yyyyMMdd')
		SET @DATA = @DATAINICIAL
		SET @COD_SEMANA =DATEPART(WEEK, @DATA)
		SET @DIA_SEMANA = DATEPART(WEEKDAY, @DATA)
		SET @NOME_DIA_SEMANA =
			CASE 
				WHEN @DIA_SEMANA = '1' THEN 'Domingo'
				WHEN @DIA_SEMANA = '2' THEN 'Segunda'
				WHEN @DIA_SEMANA = '3' THEN 'Terça'
				WHEN @DIA_SEMANA = '4' THEN 'Quarta'
				WHEN @DIA_SEMANA = '5' THEN 'Quinta'
				WHEN @DIA_SEMANA = '6' THEN 'Sexta'
				ELSE 'Sábado'
			END
		SET @DIA = DAY(@DATA)
		SET @MES= MONTH(@DATA)
		SET @NOME_MES = 
			CASE
				WHEN @MES =  '1' THEN 'Janeiro'
				WHEN @MES =  '2' THEN 'Fevereiro'
				WHEN @MES =  '3' THEN 'Março'
				WHEN @MES =  '4' THEN 'Abril'
				WHEN @MES =  '5' THEN 'Maio'
				WHEN @MES =  '6' THEN 'Junho'
				WHEN @MES =  '7' THEN 'Julho'
				WHEN @MES =  '8' THEN 'Agosto'
				WHEN @MES =  '9' THEN 'Setembro'
				WHEN @MES = '10' THEN 'Outubro'
				WHEN @MES = '11' THEN 'Novembro'
				ELSE 'Dezembro'
			END
		SET @MES_ANO = CONCAT(CONVERT(CHAR(2), @DATA, 101),' - ',YEAR(@DATA)) -- 01-2021
		SET @NOME_MES_ANO = CONCAT(@NOME_MES, ' - ',YEAR(@DATA))-- Janeiro 2021 
		SET @TRIMESTRE = 
			CASE	
				WHEN @MES IN (1,2,3) THEN 1
				WHEN @MES IN (4,5,6) THEN 2
				WHEN @MES IN (7,8,9) THEN 3
				ELSE 4
			END
		SET @NOME_TRIMESTRE =
		CASE
			WHEN @TRIMESTRE = 1 THEN 'Primeiro Trimestre'
			WHEN @TRIMESTRE = 2 THEN 'Segundo Trimestre'
			WHEN @TRIMESTRE = 3 THEN 'Terceiro Trimestre'
			ELSE 'Quarto Trimestre'
		END
		SET @TRIMESTRE_ANO = CONCAT(CONCAT('0',CONVERT(CHAR(2), @TRIMESTRE)),'- ',YEAR(@DATA))-- 01-2021
		SET @NOME_TRIMESTRE_ANO = CONCAT(@NOME_TRIMESTRE, ' ',YEAR(@DATA)) --Terceiro Trimestre 2021 
		SET @SEMESTRE = IIF(@MES IN(1,2,3,4,5,6),1,2)
		SET @NOME_SEMESTRE = IIF(@SEMESTRE IN(1), 'Primeiro Semestre', 'Segundo Semestre')
		SET @SEMESTRE_ANO = CONCAT(CONCAT('0',CONVERT(CHAR(2), @SEMESTRE)),'- ',YEAR(@DATA))
		SET @NOME_SEMESTRE_ANO = CONCAT(@NOME_SEMESTRE, ' ', YEAR(@DATA)) --Segundo Semestre 2021
		SET @ANO = YEAR(@DATA)
		SET @TIPO_DIA = IIF(@DIA_SEMANA IN(1,7),'Dia não Útil','Dia Útil')

		INSERT INTO DIM_TEMPO
			SELECT	
				@SK_DATA,
				@DATA,
				@COD_SEMANA,
				@DIA_SEMANA,
				@NOME_DIA_SEMANA,
				@DIA,
				@MES,
				@NOME_MES,
				@MES_ANO,
				@NOME_MES_ANO,
				@TRIMESTRE,
				@NOME_TRIMESTRE,
				@TRIMESTRE_ANO,
				@NOME_TRIMESTRE_ANO,
				@SEMESTRE,
				@NOME_SEMESTRE,
				@SEMESTRE_ANO,
				@NOME_SEMESTRE_ANO,
				@ANO,
				@TIPO_DIA
							   
			SET @DATAINICIAL = DATEADD(DAY,1,@DATAINICIAL)	
	
	END
END

--Testando a Procedure
--EXEC SP_INSERT_DIM_TEMPO '2015-01-01', '2017-12-27'



