USE [STAGING_VESTIBULAR]
GO

/****** Object:  View [dbo].[VW_ST_INSCRICOES]    Script Date: 17/10/2021 21:46:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE   VIEW [dbo].[VW_ST_INSCRICOES]
AS
SELECT 
	CAST(CANDIDATO_ID AS INTEGER) AS CANDIDATO_ID,
	CAST(CURSO_ID AS INTEGER) AS CURSO_ID, 
	CAST(PROCESSO_ID AS INTEGER) AS PROCESSO_ID,
	DATA_INSCRICAO,
	REPLICATE('0',4 -LEN(HORA_INSCRICAO)) + RTRIM(HORA_INSCRICAO) AS HORA_INSCRICAO,
	CAST(BOLSA_ESTUDO AS INTEGER) AS BOLSA_ESTUDO,
	CAST(CALL_CENTER AS INTEGER) AS CALL_CENTER
FROM 
	ST_INSCRICOES (NOLOCK)
WHERE DATA_INSCRICAO IS NOT NULL
GO


