USE [STAGING_VESTIBULAR]
GO

/****** Object:  View [dbo].[VW_ST_FORMA_PAGAMENTO]    Script Date: 17/10/2021 21:45:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_ST_FORMA_PAGAMENTO]
AS

SELECT DISTINCT
	CAST(FORMA_PAGAMENTO_ID AS INTEGER) AS FORMA_PAGAMENTO_ID,
	FORMA_PAGAMENTO
FROM
	ST_FORMA_PAGAMENTO (NOLOCK)
WHERE 
	FORMA_PAGAMENTO_ID IS NOT NULL
GO


