USE [STAGING_VESTIBULAR]
GO

/****** Object:  View [dbo].[VW_ST_PRE_INSCRICOES]    Script Date: 17/10/2021 21:46:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VW_ST_PRE_INSCRICOES]
AS
SELECT 
	CAST(CANDIDATO_ID AS INTEGER) AS CANDIDATO_ID,
	CAST(CURSO_ID AS INTEGER) AS CURSO_ID, 
	CAST(PROCESSO_ID AS INTEGER) AS PROCESSO_ID,
	DATA_PREINSCRICAO AS DATA_PRE_INSCRICAO,
	REPLICATE('0',4 -LEN(HORA_PREINSCRICAO)) + RTRIM(HORA_PREINSCRICAO) AS HORA_PRE_INSCRICAO
FROM 
	ST_PRE_INSCRICOES
GO


