USE [STAGING_VESTIBULAR]
GO

/****** Object:  View [dbo].[VW_ST_PROCESSO]    Script Date: 17/10/2021 21:47:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_ST_PROCESSO]
AS

SELECT DISTINCT
	CAST(PROCESSO_ID AS INTEGER) AS PROCESSO_ID,
	PROCESSO,
	PERIODO_LETIVO
FROM
	ST_PROCESSO (NOLOCK)
GO


